"""initial schema

Revision ID: d0cf68ed0d23
Revises: 
Create Date: 2026-09-11 00:35:31.714279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.crypto import EncryptedText


# revision identifiers, used by Alembic.
revision: str = 'd0cf68ed0d23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_account_credentials',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('connected_email_address', sa.String(length=256), nullable=False),
    sa.Column('business_name', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', EncryptedText(), nullable=False),
    sa.Column('access_token', EncryptedText(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('pending_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('email_reply', 'scheduling_proposal', name='actionkind'), nullable=False),
    sa.Column('source_message_id', sa.String(length=256), nullable=False),
    sa.Column('reply_to', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('state', sa.Enum('received', 'classified', 'drafted', 'awaiting_approval', 'approved', 'rejected', 'sent', 'failed', name='actionstate'), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'edited', 'rejected', name='decisiontype'), nullable=True),
    sa.Column('decided_by', sa.String(length=256), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_source_message_id'), 'pending_actions', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_tenant_id'), 'pending_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_actions_tenant_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_source_message_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_table('gmail_account_credentials')
    # ### end Alembic commands ###
