"""
Unified entry point for LLM calls. Wraps three things:

1. Streaming output (AsyncGenerator[str]), for the SSE route to pass straight through to the frontend.
2. Automatic fallback to a backup model when the primary model fails (provider-level failover — a
   common interview question is "what if OpenAI/Anthropic goes down").
3. Exponential-backoff retry (tenacity), retrying only "retryable" errors (timeouts/rate limits), not
   content-related errors.
"""
from __future__ import annotations

from collections.abc import AsyncGenerator

import anthropic
import structlog
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from app.core.config import Settings

logger = structlog.get_logger()


class RetryableLLMError(Exception):
    """Rate limit / timeout / 5xx — errors worth retrying."""


class LLMClient:
    def __init__(self, settings: Settings):
        self._settings = settings
        self._primary = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    @retry(
        retry=retry_if_exception_type(RetryableLLMError),
        wait=wait_exponential(multiplier=0.5, max=8),
        stop=stop_after_attempt(3),
        reraise=True,
    )
    async def _stream_primary(self, system: str, prompt: str) -> AsyncGenerator[str, None]:
        try:
            async with self._primary.messages.stream(
                model=self._settings.primary_model,
                max_tokens=512,
                system=system,
                messages=[{"role": "user", "content": prompt}],
            ) as stream:
                async for text in stream.text_stream:
                    yield text
        except (anthropic.RateLimitError, anthropic.APITimeoutError, anthropic.InternalServerError) as e:
            raise RetryableLLMError(str(e)) from e

    async def stream_reply_draft(self, system: str, prompt: str) -> AsyncGenerator[str, None]:
        """
        The single externally exposed entry point. Tries the primary model first; if it still fails
        after multiple retries, falls back to the backup model. The fallback logic lives here rather
        than in the routing layer, so the caller (the API layer) never needs to be aware of provider
        details.
        """
        try:
            async for chunk in self._stream_primary(system, prompt):
                yield chunk
            return
        except Exception:
            logger.warning("primary_model_failed_falling_back", model=self._settings.primary_model)

        # The fallback model is non-streaming (simplified for the skeleton; in production, swap in the OpenAI streaming SDK)
        yield "[fallback] "
        yield "The primary model is temporarily unavailable; switched to a brief reply draft generated by the fallback model."
